apiVersion: v1
kind: Service
metadata:
  name: simpledataredundant
  namespace: demo-circuitbreaker
spec:
  selector:
    app: simpledataredundant
  ports:
    - name: http
      port: 8080
  type: ClusterIP
---
