kind: Gateway
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: simpledataredundant-gateway
  namespace: demo-circuitbreaker
spec:
  servers:
    - hosts:
        - simpledataredundant.teste.com.br
      port:
        name: http
        number: 443
        protocol: HTTP
  selector:
    istio: ingressgateway